version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: ofmi_db
    restart: always
    environment:
      - POSTGRES_USER=void
      - POSTGRES_PASSWORD=void
      - POSTGRES_DB=void
    ports:
      - '5001:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
